apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: shared-vast
  volumeName: pvc-389599c1-e2c8-4f33-953e-4b85362027b9
  resources:
    requests:
      storage: 5000Gi
